---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
  namespace: twang0
  labels:
    app: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
        - name: project
          image: w255mids.azurecr.io/twang0/cap-temp:fa6017a
          env:
            - name: REDIS_URL
              value: redis://redis:6379
          resources:
            requests:
              cpu: 400m
              memory: 1000Mi
            limits:
              cpu: 1000m
              memory: 2000Mi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
      initContainers:
        - name: init-verify-redis-service-dns
          image: busybox
          resources:
            limits:
              cpu: '2'
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          command:
            [
              "sh",
              "-c",
              "until nc -vz redis 6379; do echo 'waiting for redis service from DNS'; sleep 2; done",
            ]
        - name: init-verify-redis-ready
          image: busybox
          resources:
            limits:
              cpu: '2'
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          command:
            [
              "sh",
              "-c",
              "until (printf 'PING\r\n';) | nc redis 6379; do echo 'waiting for redis to PONG'; sleep 1; done",
            ]
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: project
  namespace: twang0
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: project
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50
